<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Afghanistan 93</name>
   <tag></tag>
   <elementGuidId>9b6c6cc6-a1c0-431d-8b89-a101e9e6c50b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-country-picker_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='auth-country-picker_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>10c266ba-ef14-4236-bd6f-7dbe235cb857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b9279a94-e57a-4d4b-8e9b-9d6efeaa96b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>847cc6a2-6e8d-4946-b72d-9cc9968fcdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;AF&quot;}</value>
      <webElementGuid>cb49176d-73aa-4dad-b4a3-29e963fcad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-country-picker_0</value>
      <webElementGuid>b39868c6-1c04-42c8-adfb-da69654289ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>8528c0f2-6f96-493c-a7c4-b5278c308d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Afghanistan +93</value>
      <webElementGuid>0a2da997-53a0-4b02-b61c-aeaca1a285ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-country-picker_0&quot;)</value>
      <webElementGuid>a865a15f-f21a-4ab0-9cd8-4afa4b36a0d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='auth-country-picker_0']</value>
      <webElementGuid>5bb4fac9-4ce5-4884-8c16-475d11d919ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/div/ul/li/a</value>
      <webElementGuid>ca3a43b4-c498-4bc0-b7d0-51c9819a768d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Afghanistan +93')]</value>
      <webElementGuid>d0fffc02-f9df-49a1-93c0-3b1ff668594d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'auth-country-picker_0', '&quot;', ')')])[1]/following::a[1]</value>
      <webElementGuid>bf161eb6-ef4c-4beb-a083-ff8ba82907eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 1996-2023, Amazon.com, Inc. or its affiliates'])[1]/following::a[1]</value>
      <webElementGuid>a2ecb49f-13ea-4cd6-bc1a-15c90fa5357f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Albania +355'])[1]/preceding::a[1]</value>
      <webElementGuid>2ccfb3bf-8a1a-4924-b8b0-e5a4cb48e979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Algeria +213'])[1]/preceding::a[2]</value>
      <webElementGuid>60be1e98-c281-4119-b5cc-723996ba916a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Afghanistan +93']/parent::*</value>
      <webElementGuid>7c98b30b-17db-4c06-8657-3a4bd8b3cd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>01a6f32c-d64d-4272-b5f0-794b96d138b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>0cd48ec4-b42a-4bae-93b3-46e6a394f77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'auth-country-picker_0' and (text() = 'Afghanistan +93' or . = 'Afghanistan +93')]</value>
      <webElementGuid>3cf5c758-b0cf-460a-9213-81ad1b2f172c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
