<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_India 91</name>
   <tag></tag>
   <elementGuidId>0594b82f-ebf8-4380-abf6-2748b865c6ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-country-picker_92</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='auth-country-picker_92']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>045c4179-2684-41d2-87da-2342d958c033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f9167d59-4808-42a0-8139-df4b0ecfae3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>466c7417-7035-4848-a238-83710b0485c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;IN&quot;}</value>
      <webElementGuid>189bcfa8-5c25-4db4-9c6d-fb23497f662d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-country-picker_92</value>
      <webElementGuid>8377ca1b-7d30-4659-8a42-431a5cfc6f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>f88dbba7-a4c9-4467-ae9c-d1523344e43d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>India +91</value>
      <webElementGuid>d424196e-bb3f-4ce3-9a00-de2d4366d61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-country-picker_92&quot;)</value>
      <webElementGuid>1406a2aa-1a9b-4f1c-8f60-edb464eb5022</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='auth-country-picker_92']</value>
      <webElementGuid>0ad7523f-90b2-4227-afbb-70292d6082d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-1']/div/div/ul/li[93]/a</value>
      <webElementGuid>c7b0f828-8760-43ed-967c-c537760c2c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'India +91')]</value>
      <webElementGuid>61ca7ed7-f1ed-4d44-98ef-926152044202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iceland +354'])[1]/following::a[1]</value>
      <webElementGuid>6261019d-b3b6-4f83-b0a1-c6b142f80d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hungary +36'])[1]/following::a[2]</value>
      <webElementGuid>06596946-cc7e-4ba5-b8c1-2ba664a648a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia +62'])[1]/preceding::a[1]</value>
      <webElementGuid>1a7c61c5-86fa-454e-9a97-86601642abc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iran +98'])[1]/preceding::a[2]</value>
      <webElementGuid>17f08deb-61e3-4e44-8dff-f55fac11953d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='India +91']/parent::*</value>
      <webElementGuid>86959d1b-6a95-4f3d-b892-33fe86dc45ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[93]</value>
      <webElementGuid>0b66a0d4-c935-4bad-9e1d-7424d9a1a925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[93]/a</value>
      <webElementGuid>0477bd67-1a0c-4454-8322-32bea78791cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'auth-country-picker_92' and (text() = 'India +91' or . = 'India +91')]</value>
      <webElementGuid>071b3af2-b18f-4707-b582-9f9b97910fc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
