<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AF 93</name>
   <tag></tag>
   <elementGuidId>bd872b14-2ba2-435d-9206-d2edf5cd205f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-section.country-picker > span.a-declarative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ap_register_form']/div/div/div[2]/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fca47a1-21d1-41df-932d-df07c0848156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-declarative</value>
      <webElementGuid>1fcff2da-50c5-45f9-af09-363056430ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>show-countries</value>
      <webElementGuid>3a127455-22f1-4a9f-93b8-b226d7fe5f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>0465ee95-4db4-40c4-97e0-8a7e4a6e7a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-func-deps</name>
      <type>Main</type>
      <value>aui-da-show-countries</value>
      <webElementGuid>78877847-8916-4eaf-938f-b177a37bf2c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show-countries</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>14edcd0f-dafc-4646-ac1f-9dd4891d1c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>gfa3ig-ju9866-g1rvd8-f2e6pd</value>
      <webElementGuid>cb287e16-ba38-487a-95b0-bcb1f2a6066f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AF +93</value>
      <webElementGuid>3f5b3304-8bbb-4a10-828e-8023b8200d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ap_register_form&quot;)/div[@class=&quot;a-box a-spacing-extra-large&quot;]/div[@class=&quot;a-box-inner&quot;]/div[@class=&quot;a-section a-spacing-base moa-single-claim-container&quot;]/div[@class=&quot;a-section a-spacing-none moa-single-claim-input-container&quot;]/div[@class=&quot;a-section country-picker&quot;]/span[@class=&quot;a-declarative&quot;]</value>
      <webElementGuid>b0d8232b-f63f-4704-9da4-2f2bdab93fde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ap_register_form']/div/div/div[2]/div[2]/div/span</value>
      <webElementGuid>3258c9b2-4515-4169-bdb8-6408f55581c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AF +93'])[2]/following::span[2]</value>
      <webElementGuid>05036b9f-2999-45e9-8e6c-0196291f4dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile number or email'])[1]/following::span[7]</value>
      <webElementGuid>08bf3a6f-a41b-46a4-9934-6416bf3de99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your email or mobile phone number'])[1]/preceding::span[1]</value>
      <webElementGuid>f8f9e6f2-f06e-4080-9516-060145955db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wrong or Invalid email address or mobile phone number. Please correct and try again.'])[1]/preceding::span[1]</value>
      <webElementGuid>def6b784-e9f4-4d5f-92bf-9d84b1daccc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span</value>
      <webElementGuid>f1a927bf-b66b-4eb7-9b1a-a3e4b2e08015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AF +93' or . = 'AF +93')]</value>
      <webElementGuid>d7754a72-8610-4cd0-888d-5994eb54e0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
